/**
 * 共享单车api
 * Android、iOS操作类
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BicycleBO', 'model/CouponBO', 'model/ListResponseOfBicycleBO', 'model/MemberBO', 'model/MultipartFile', 'model/OngoingInfoBO', 'model/PageResponseOfCouponBO', 'model/PageResponseOfTripBO', 'model/PageResponseOfUserDepositLogBO', 'model/Point', 'model/RequestResult', 'model/ReserveBO', 'model/SimpleResponse', 'model/SingleResponseOfMemberBO', 'model/SingleResponseOfOngoingInfoBO', 'model/SingleResponseOfRequestResult', 'model/SingleResponseOfThirdPartyBoundModileBO', 'model/SingleResponseOfWeiXinPaymetBO', 'model/ThirdPartyBoundModileBO', 'model/TripBO', 'model/UserDepositLogBO', 'model/WeiXinPaymetBO', 'api/BicyclecontrollerApi', 'api/FileuploadcontrollerApi', 'api/TripcontrollerApi', 'api/UsercontrollerApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/BicycleBO'), require('./model/CouponBO'), require('./model/ListResponseOfBicycleBO'), require('./model/MemberBO'), require('./model/MultipartFile'), require('./model/OngoingInfoBO'), require('./model/PageResponseOfCouponBO'), require('./model/PageResponseOfTripBO'), require('./model/PageResponseOfUserDepositLogBO'), require('./model/Point'), require('./model/RequestResult'), require('./model/ReserveBO'), require('./model/SimpleResponse'), require('./model/SingleResponseOfMemberBO'), require('./model/SingleResponseOfOngoingInfoBO'), require('./model/SingleResponseOfRequestResult'), require('./model/SingleResponseOfThirdPartyBoundModileBO'), require('./model/SingleResponseOfWeiXinPaymetBO'), require('./model/ThirdPartyBoundModileBO'), require('./model/TripBO'), require('./model/UserDepositLogBO'), require('./model/WeiXinPaymetBO'), require('./api/BicyclecontrollerApi'), require('./api/FileuploadcontrollerApi'), require('./api/TripcontrollerApi'), require('./api/UsercontrollerApi'));
  }
}(function(ApiClient, BicycleBO, CouponBO, ListResponseOfBicycleBO, MemberBO, MultipartFile, OngoingInfoBO, PageResponseOfCouponBO, PageResponseOfTripBO, PageResponseOfUserDepositLogBO, Point, RequestResult, ReserveBO, SimpleResponse, SingleResponseOfMemberBO, SingleResponseOfOngoingInfoBO, SingleResponseOfRequestResult, SingleResponseOfThirdPartyBoundModileBO, SingleResponseOfWeiXinPaymetBO, ThirdPartyBoundModileBO, TripBO, UserDepositLogBO, WeiXinPaymetBO, BicyclecontrollerApi, FileuploadcontrollerApi, TripcontrollerApi, UsercontrollerApi) {
  'use strict';

  /**
   * AndroidiOS.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Api = require('index'); // See note below*.
   * var xxxSvc = new Api.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Api.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Api.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Api.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The BicycleBO model constructor.
     * @property {module:model/BicycleBO}
     */
    BicycleBO: BicycleBO,
    /**
     * The CouponBO model constructor.
     * @property {module:model/CouponBO}
     */
    CouponBO: CouponBO,
    /**
     * The ListResponseOfBicycleBO model constructor.
     * @property {module:model/ListResponseOfBicycleBO}
     */
    ListResponseOfBicycleBO: ListResponseOfBicycleBO,
    /**
     * The MemberBO model constructor.
     * @property {module:model/MemberBO}
     */
    MemberBO: MemberBO,
    /**
     * The MultipartFile model constructor.
     * @property {module:model/MultipartFile}
     */
    MultipartFile: MultipartFile,
    /**
     * The OngoingInfoBO model constructor.
     * @property {module:model/OngoingInfoBO}
     */
    OngoingInfoBO: OngoingInfoBO,
    /**
     * The PageResponseOfCouponBO model constructor.
     * @property {module:model/PageResponseOfCouponBO}
     */
    PageResponseOfCouponBO: PageResponseOfCouponBO,
    /**
     * The PageResponseOfTripBO model constructor.
     * @property {module:model/PageResponseOfTripBO}
     */
    PageResponseOfTripBO: PageResponseOfTripBO,
    /**
     * The PageResponseOfUserDepositLogBO model constructor.
     * @property {module:model/PageResponseOfUserDepositLogBO}
     */
    PageResponseOfUserDepositLogBO: PageResponseOfUserDepositLogBO,
    /**
     * The Point model constructor.
     * @property {module:model/Point}
     */
    Point: Point,
    /**
     * The RequestResult model constructor.
     * @property {module:model/RequestResult}
     */
    RequestResult: RequestResult,
    /**
     * The ReserveBO model constructor.
     * @property {module:model/ReserveBO}
     */
    ReserveBO: ReserveBO,
    /**
     * The SimpleResponse model constructor.
     * @property {module:model/SimpleResponse}
     */
    SimpleResponse: SimpleResponse,
    /**
     * The SingleResponseOfMemberBO model constructor.
     * @property {module:model/SingleResponseOfMemberBO}
     */
    SingleResponseOfMemberBO: SingleResponseOfMemberBO,
    /**
     * The SingleResponseOfOngoingInfoBO model constructor.
     * @property {module:model/SingleResponseOfOngoingInfoBO}
     */
    SingleResponseOfOngoingInfoBO: SingleResponseOfOngoingInfoBO,
    /**
     * The SingleResponseOfRequestResult model constructor.
     * @property {module:model/SingleResponseOfRequestResult}
     */
    SingleResponseOfRequestResult: SingleResponseOfRequestResult,
    /**
     * The SingleResponseOfThirdPartyBoundModileBO model constructor.
     * @property {module:model/SingleResponseOfThirdPartyBoundModileBO}
     */
    SingleResponseOfThirdPartyBoundModileBO: SingleResponseOfThirdPartyBoundModileBO,
    /**
     * The SingleResponseOfWeiXinPaymetBO model constructor.
     * @property {module:model/SingleResponseOfWeiXinPaymetBO}
     */
    SingleResponseOfWeiXinPaymetBO: SingleResponseOfWeiXinPaymetBO,
    /**
     * The ThirdPartyBoundModileBO model constructor.
     * @property {module:model/ThirdPartyBoundModileBO}
     */
    ThirdPartyBoundModileBO: ThirdPartyBoundModileBO,
    /**
     * The TripBO model constructor.
     * @property {module:model/TripBO}
     */
    TripBO: TripBO,
    /**
     * The UserDepositLogBO model constructor.
     * @property {module:model/UserDepositLogBO}
     */
    UserDepositLogBO: UserDepositLogBO,
    /**
     * The WeiXinPaymetBO model constructor.
     * @property {module:model/WeiXinPaymetBO}
     */
    WeiXinPaymetBO: WeiXinPaymetBO,
    /**
     * The BicyclecontrollerApi service constructor.
     * @property {module:api/BicyclecontrollerApi}
     */
    BicyclecontrollerApi: BicyclecontrollerApi,
    /**
     * The FileuploadcontrollerApi service constructor.
     * @property {module:api/FileuploadcontrollerApi}
     */
    FileuploadcontrollerApi: FileuploadcontrollerApi,
    /**
     * The TripcontrollerApi service constructor.
     * @property {module:api/TripcontrollerApi}
     */
    TripcontrollerApi: TripcontrollerApi,
    /**
     * The UsercontrollerApi service constructor.
     * @property {module:api/UsercontrollerApi}
     */
    UsercontrollerApi: UsercontrollerApi
  };

  return exports;
}));
