/**
 * 彩虹共享雨金箍棒api
 * Android、iOS操作类
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SingleResponseOfApiActivityBO', 'model/SimpleResponse', 'model/ListResponseOfApiActivityBO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/SingleResponseOfApiActivityBO'), require('../model/SimpleResponse'), require('../model/ListResponseOfApiActivityBO'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.ActivitycontrollerApi = factory(root.Api.ApiClient, root.Api.SingleResponseOfApiActivityBO, root.Api.SimpleResponse, root.Api.ListResponseOfApiActivityBO);
  }
}(this, function(ApiClient, SingleResponseOfApiActivityBO, SimpleResponse, ListResponseOfApiActivityBO) {
  'use strict';

  /**
   * Activitycontroller service.
   * @module api/ActivitycontrollerApi
   * @version 1.0
   */

  /**
   * Constructs a new ActivitycontrollerApi. 
   * @alias module:api/ActivitycontrollerApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the activityDetailUsingPOST operation.
     * @callback module:api/ActivitycontrollerApi~activityDetailUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SingleResponseOfApiActivityBO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 活动详情
     * @param {Integer} id 活动id
     * @param {Object} opts Optional parameters
     * @param {Integer} opts.suid 用户id，小程序分享时上送
     * @param {String} opts.pointType 坐标系类型,默认百度坐标（BD09）、国测局坐标（火星坐标，GCJ02）、和WGS84坐标系之间的转换的工具
     * @param {module:api/ActivitycontrollerApi~activityDetailUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SingleResponseOfApiActivityBO}
     */
    this.activityDetailUsingPOST = function(id, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling activityDetailUsingPOST";
      }


      var pathParams = {
      };
      var queryParams = {
        'id': id,
        'suid': opts['suid'],
        'pointType': opts['pointType']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2-password'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SingleResponseOfApiActivityBO;

      return this.apiClient.callApi(
        '/api/activity/activityDetail', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the addShareTimesUsingPOST operation.
     * @callback module:api/ActivitycontrollerApi~addShareTimesUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SimpleResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 增加活动分享次数
     * 增加活动分享次数
     * @param {Integer} id 活动id
     * @param {module:api/ActivitycontrollerApi~addShareTimesUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SimpleResponse}
     */
    this.addShareTimesUsingPOST = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling addShareTimesUsingPOST";
      }


      var pathParams = {
      };
      var queryParams = {
        'id': id
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2-password'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SimpleResponse;

      return this.apiClient.callApi(
        '/api/activity/addShareTimes', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the listActivityUsingPOST operation.
     * @callback module:api/ActivitycontrollerApi~listActivityUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ListResponseOfApiActivityBO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 活动列表查询
     * @param {String} type 活动类型，today 今日活动 , history历史活动
     * @param {module:api/ActivitycontrollerApi~listActivityUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ListResponseOfApiActivityBO}
     */
    this.listActivityUsingPOST = function(type, callback) {
      var postBody = null;

      // verify the required parameter 'type' is set
      if (type == undefined || type == null) {
        throw "Missing the required parameter 'type' when calling listActivityUsingPOST";
      }


      var pathParams = {
      };
      var queryParams = {
        'type': type
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2-password'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ListResponseOfApiActivityBO;

      return this.apiClient.callApi(
        '/api/activity/listActivity', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
