/**
 * 彩虹共享雨金箍棒api
 * Android、iOS操作类
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SingleResponseOfAPIUmOrderBO', 'model/SingleResponseOfAPISwingCardBO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/SingleResponseOfAPIUmOrderBO'), require('../model/SingleResponseOfAPISwingCardBO'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.AgentbizcontrollerApi = factory(root.Api.ApiClient, root.Api.SingleResponseOfAPIUmOrderBO, root.Api.SingleResponseOfAPISwingCardBO);
  }
}(this, function(ApiClient, SingleResponseOfAPIUmOrderBO, SingleResponseOfAPISwingCardBO) {
  'use strict';

  /**
   * Agentbizcontroller service.
   * @module api/AgentbizcontrollerApi
   * @version 1.0
   */

  /**
   * Constructs a new AgentbizcontrollerApi. 
   * @alias module:api/AgentbizcontrollerApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the findOrderResultUsingGET operation.
     * @callback module:api/AgentbizcontrollerApi~findOrderResultUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SingleResponseOfAPIUmOrderBO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 订单结果
     * @param {String} borrowQrCode 借金箍棒二维码
     * @param {module:api/AgentbizcontrollerApi~findOrderResultUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SingleResponseOfAPIUmOrderBO}
     */
    this.findOrderResultUsingGET = function(borrowQrCode, callback) {
      var postBody = null;

      // verify the required parameter 'borrowQrCode' is set
      if (borrowQrCode == undefined || borrowQrCode == null) {
        throw "Missing the required parameter 'borrowQrCode' when calling findOrderResultUsingGET";
      }


      var pathParams = {
      };
      var queryParams = {
        'borrowQrCode': borrowQrCode
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2-password'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SingleResponseOfAPIUmOrderBO;

      return this.apiClient.callApi(
        '/api/agent_biz/find_order_result', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the swingCardUsingPOST operation.
     * @callback module:api/AgentbizcontrollerApi~swingCardUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SingleResponseOfAPISwingCardBO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 刷卡
     * @param {String} assetNumber 棒机编号
     * @param {module:api/AgentbizcontrollerApi~swingCardUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SingleResponseOfAPISwingCardBO}
     */
    this.swingCardUsingPOST = function(assetNumber, callback) {
      var postBody = null;

      // verify the required parameter 'assetNumber' is set
      if (assetNumber == undefined || assetNumber == null) {
        throw "Missing the required parameter 'assetNumber' when calling swingCardUsingPOST";
      }


      var pathParams = {
      };
      var queryParams = {
        'assetNumber': assetNumber
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2-password'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SingleResponseOfAPISwingCardBO;

      return this.apiClient.callApi(
        '/api/agent_biz/swing_card', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
