/**
 * 彩虹共享雨金箍棒api
 * Android、iOS操作类
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SingleResponseOfShareSetBO', 'model/SingleResponseOfImgBo', 'model/SingleResponseOfSysSettingBO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/SingleResponseOfShareSetBO'), require('../model/SingleResponseOfImgBo'), require('../model/SingleResponseOfSysSettingBO'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.AppparamcontrollerApi = factory(root.Api.ApiClient, root.Api.SingleResponseOfShareSetBO, root.Api.SingleResponseOfImgBo, root.Api.SingleResponseOfSysSettingBO);
  }
}(this, function(ApiClient, SingleResponseOfShareSetBO, SingleResponseOfImgBo, SingleResponseOfSysSettingBO) {
  'use strict';

  /**
   * Appparamcontroller service.
   * @module api/AppparamcontrollerApi
   * @version 1.0
   */

  /**
   * Constructs a new AppparamcontrollerApi. 
   * @alias module:api/AppparamcontrollerApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the queryAppShareUsingGET operation.
     * @callback module:api/AppparamcontrollerApi~queryAppShareUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SingleResponseOfShareSetBO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 查询分享或邀请相关设置
     * 查询分享或邀请相关设置
     * @param {module:api/AppparamcontrollerApi~queryAppShareUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SingleResponseOfShareSetBO}
     */
    this.queryAppShareUsingGET = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2-clientcredentials'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SingleResponseOfShareSetBO;

      return this.apiClient.callApi(
        '/api/param/query_app_share', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the queryInitImgUsingGET operation.
     * @callback module:api/AppparamcontrollerApi~queryInitImgUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SingleResponseOfImgBo} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 查询app启动时图片
     * 查询app启动时图片
     * @param {module:api/AppparamcontrollerApi~queryInitImgUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SingleResponseOfImgBo}
     */
    this.queryInitImgUsingGET = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2-clientcredentials'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SingleResponseOfImgBo;

      return this.apiClient.callApi(
        '/api/param/query_app_img', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the querySysSetUsingGET operation.
     * @callback module:api/AppparamcontrollerApi~querySysSetUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SingleResponseOfSysSettingBO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 查询系统配置相关
     * 查询系统配置相关（支付方式，联系我们电话，默认语言等）
     * @param {module:api/AppparamcontrollerApi~querySysSetUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SingleResponseOfSysSettingBO}
     */
    this.querySysSetUsingGET = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2-clientcredentials'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SingleResponseOfSysSettingBO;

      return this.apiClient.callApi(
        '/api/param/query_sys_set', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
