/**
 * 彩虹共享雨金箍棒api
 * Android、iOS操作类
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SingleResponseOfAPIUmOrderBO', 'model/PageResponseOfAPIUmOrderBO', 'model/ListResponseOfUserCouponBO', 'model/SingleResponseOfPayDetailsBO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/SingleResponseOfAPIUmOrderBO'), require('../model/PageResponseOfAPIUmOrderBO'), require('../model/ListResponseOfUserCouponBO'), require('../model/SingleResponseOfPayDetailsBO'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.UmordercontrollerApi = factory(root.Api.ApiClient, root.Api.SingleResponseOfAPIUmOrderBO, root.Api.PageResponseOfAPIUmOrderBO, root.Api.ListResponseOfUserCouponBO, root.Api.SingleResponseOfPayDetailsBO);
  }
}(this, function(ApiClient, SingleResponseOfAPIUmOrderBO, PageResponseOfAPIUmOrderBO, ListResponseOfUserCouponBO, SingleResponseOfPayDetailsBO) {
  'use strict';

  /**
   * Umordercontroller service.
   * @module api/UmordercontrollerApi
   * @version 1.0
   */

  /**
   * Constructs a new UmordercontrollerApi. 
   * @alias module:api/UmordercontrollerApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createOrderUsingPOST operation.
     * @callback module:api/UmordercontrollerApi~createOrderUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SingleResponseOfAPIUmOrderBO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 创建订单
     * @param {String} qrCode 二维码
     * @param {module:api/UmordercontrollerApi~createOrderUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SingleResponseOfAPIUmOrderBO}
     */
    this.createOrderUsingPOST = function(qrCode, callback) {
      var postBody = null;

      // verify the required parameter 'qrCode' is set
      if (qrCode == undefined || qrCode == null) {
        throw "Missing the required parameter 'qrCode' when calling createOrderUsingPOST";
      }


      var pathParams = {
      };
      var queryParams = {
        'qrCode': qrCode
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2-password'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SingleResponseOfAPIUmOrderBO;

      return this.apiClient.callApi(
        '/api/order/create', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the findAgnetOrderUsingPOST operation.
     * @callback module:api/UmordercontrollerApi~findAgnetOrderUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PageResponseOfAPIUmOrderBO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 代理商订单列表,beginTime 降序排列,权限：代理点管理用户
     * @param {String} type 类型,borrow 借，return 还
     * @param {Object} opts Optional parameters
     * @param {String} opts.mobile 个人用户手机号
     * @param {Integer} opts.beginTime 开始时间
     * @param {Integer} opts.endTime 结束时间
     * @param {Integer} opts.ltTime 结束时间的排序
     * @param {String} opts.pointType 坐标系类型,默认百度坐标（BD09）、国测局坐标（火星坐标，GCJ02）、WGS84
     * @param {module:api/UmordercontrollerApi~findAgnetOrderUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PageResponseOfAPIUmOrderBO}
     */
    this.findAgnetOrderUsingPOST = function(type, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'type' is set
      if (type == undefined || type == null) {
        throw "Missing the required parameter 'type' when calling findAgnetOrderUsingPOST";
      }


      var pathParams = {
      };
      var queryParams = {
        'type': type,
        'mobile': opts['mobile'],
        'beginTime': opts['beginTime'],
        'endTime': opts['endTime'],
        'ltTime': opts['ltTime'],
        'pointType': opts['pointType']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2-password'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = PageResponseOfAPIUmOrderBO;

      return this.apiClient.callApi(
        '/api/order/agnet_order_list', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the findCouponListUsingPOST operation.
     * @callback module:api/UmordercontrollerApi~findCouponListUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ListResponseOfUserCouponBO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 未支付订单优惠券列表
     * @param {module:api/UmordercontrollerApi~findCouponListUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ListResponseOfUserCouponBO}
     */
    this.findCouponListUsingPOST = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2-password'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ListResponseOfUserCouponBO;

      return this.apiClient.callApi(
        '/api/order/coupon_list', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the findDoingInfoUsingGET operation.
     * @callback module:api/UmordercontrollerApi~findDoingInfoUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SingleResponseOfAPIUmOrderBO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 进行中订单信息
     * @param {Object} opts Optional parameters
     * @param {String} opts.pointType 坐标系类型,默认百度坐标（BD09）、国测局坐标（火星坐标，GCJ02）、WGS84
     * @param {module:api/UmordercontrollerApi~findDoingInfoUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SingleResponseOfAPIUmOrderBO}
     */
    this.findDoingInfoUsingGET = function (opts, callback) {
      opts = opts || {};
      var postBody = null;

      var pathParams = {
      };
      var queryParams = {
        'pointType': opts['pointType']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2-password'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SingleResponseOfAPIUmOrderBO;

      return this.apiClient.callApi(
        '/api/order/doing_info', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the findNotPayTripUsingGET operation.
     * @callback module:api/UmordercontrollerApi~findNotPayTripUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SingleResponseOfAPIUmOrderBO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 未支付的订单
     * @param {Object} opts Optional parameters
     * @param {String} opts.pointType 坐标系类型,默认百度坐标（BD09）、国测局坐标（火星坐标，GCJ02）、WGS84
     * @param {module:api/UmordercontrollerApi~findNotPayTripUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SingleResponseOfAPIUmOrderBO}
     */
    this.findNotPayTripUsingGET = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'pointType': opts['pointType']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2-password'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SingleResponseOfAPIUmOrderBO;

      return this.apiClient.callApi(
        '/api/order/not_pay_trip', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the findOrderListUsingPOST operation.
     * @callback module:api/UmordercontrollerApi~findOrderListUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PageResponseOfAPIUmOrderBO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 订单列表
     * @param {Object} opts Optional parameters
     * @param {Integer} opts.ltTime 结束时间的排序
     * @param {String} opts.pointType 坐标系类型,默认百度坐标（BD09）、国测局坐标（火星坐标，GCJ02）、WGS84
     * @param {module:api/UmordercontrollerApi~findOrderListUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PageResponseOfAPIUmOrderBO}
     */
    this.findOrderListUsingPOST = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'ltTime': opts['ltTime'],
        'pointType': opts['pointType']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2-password'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = PageResponseOfAPIUmOrderBO;

      return this.apiClient.callApi(
        '/api/order/list', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderBuyPaymetUsingPOST operation.
     * @callback module:api/UmordercontrollerApi~orderBuyPaymetUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SingleResponseOfPayDetailsBO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 订单购买支付
     * @param {String} orderCode 订单编号
     * @param {Object} opts Optional parameters
     * @param {String} opts.paymentMark 支付方式  alipay_app,wx_app,wx_js
     * @param {module:api/UmordercontrollerApi~orderBuyPaymetUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SingleResponseOfPayDetailsBO}
     */
    this.orderBuyPaymetUsingPOST = function(orderCode, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'orderCode' is set
      if (orderCode == undefined || orderCode == null) {
        throw "Missing the required parameter 'orderCode' when calling orderBuyPaymetUsingPOST";
      }


      var pathParams = {
      };
      var queryParams = {
        'orderCode': orderCode,
        'paymentMark': opts['paymentMark']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2-password'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SingleResponseOfPayDetailsBO;

      return this.apiClient.callApi(
        '/api/order/order_buy_paymet', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the paymetUsingPOST operation.
     * @callback module:api/UmordercontrollerApi~paymetUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SingleResponseOfPayDetailsBO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 支付
     * @param {String} orderCode 订单编号
     * @param {Object} opts Optional parameters
     * @param {Integer} opts.cid 优惠卷Id
     * @param {String} opts.paymentMark 支付方式  alipay_app,wx_app
     * @param {module:api/UmordercontrollerApi~paymetUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SingleResponseOfPayDetailsBO}
     */
    this.paymetUsingPOST = function(orderCode, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'orderCode' is set
      if (orderCode == undefined || orderCode == null) {
        throw "Missing the required parameter 'orderCode' when calling paymetUsingPOST";
      }


      var pathParams = {
      };
      var queryParams = {
        'orderCode': orderCode,
        'cid': opts['cid'],
        'paymentMark': opts['paymentMark'],
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2-password'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SingleResponseOfPayDetailsBO;

      return this.apiClient.callApi(
        '/api/order/paymet', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the profileUsingGET operation.
     * @callback module:api/UmordercontrollerApi~profileUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SingleResponseOfAPIUmOrderBO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 订单详情
     * @param {String} orderCode 订单编码
     * @param {Object} opts Optional parameters
     * @param {String} opts.pointType 坐标系类型,默认百度坐标（BD09）、国测局坐标（火星坐标，GCJ02）、WGS84
     * @param {module:api/UmordercontrollerApi~profileUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SingleResponseOfAPIUmOrderBO}
     */
    this.profileUsingGET = function(orderCode, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'orderCode' is set
      if (orderCode == undefined || orderCode == null) {
        throw "Missing the required parameter 'orderCode' when calling profileUsingGET";
      }


      var pathParams = {
      };
      var queryParams = {
        'orderCode': orderCode,
        'pointType': opts['pointType']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2-password'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SingleResponseOfAPIUmOrderBO;

      return this.apiClient.callApi(
        '/api/order/profile', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
