/**
 * 彩虹共享雨金箍棒api
 * Android、iOS操作类
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.APIAgentReturnUmbrellaBO = factory(root.Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The APIAgentReturnUmbrellaBO model module.
   * @module model/APIAgentReturnUmbrellaBO
   * @version 1.0
   */

  /**
   * Constructs a new <code>APIAgentReturnUmbrellaBO</code>.
   * @alias module:model/APIAgentReturnUmbrellaBO
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>APIAgentReturnUmbrellaBO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APIAgentReturnUmbrellaBO} obj Optional instance to populate.
   * @return {module:model/APIAgentReturnUmbrellaBO} The populated <code>APIAgentReturnUmbrellaBO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('createTime')) {
        obj['createTime'] = ApiClient.convertToType(data['createTime'], 'Date');
      }
      if (data.hasOwnProperty('officeId')) {
        obj['officeId'] = ApiClient.convertToType(data['officeId'], 'Integer');
      }
      if (data.hasOwnProperty('repairerId')) {
        obj['repairerId'] = ApiClient.convertToType(data['repairerId'], 'Integer');
      }
      if (data.hasOwnProperty('repairerName')) {
        obj['repairerName'] = ApiClient.convertToType(data['repairerName'], 'String');
      }
      if (data.hasOwnProperty('returnMachineCode')) {
        obj['returnMachineCode'] = ApiClient.convertToType(data['returnMachineCode'], 'String');
      }
      if (data.hasOwnProperty('returnMachineId')) {
        obj['returnMachineId'] = ApiClient.convertToType(data['returnMachineId'], 'Integer');
      }
      if (data.hasOwnProperty('returnType')) {
        obj['returnType'] = ApiClient.convertToType(data['returnType'], 'String');
      }
      if (data.hasOwnProperty('sourceAgentId')) {
        obj['sourceAgentId'] = ApiClient.convertToType(data['sourceAgentId'], 'Integer');
      }
      if (data.hasOwnProperty('sourceAgentName')) {
        obj['sourceAgentName'] = ApiClient.convertToType(data['sourceAgentName'], 'String');
      }
      if (data.hasOwnProperty('umbrellaCode')) {
        obj['umbrellaCode'] = ApiClient.convertToType(data['umbrellaCode'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Date} createTime
   */
  exports.prototype['createTime'] = undefined;
  /**
   * @member {Integer} officeId
   */
  exports.prototype['officeId'] = undefined;
  /**
   * @member {Integer} repairerId
   */
  exports.prototype['repairerId'] = undefined;
  /**
   * @member {String} repairerName
   */
  exports.prototype['repairerName'] = undefined;
  /**
   * 归还的棒机code 
   * @member {String} returnMachineCode
   */
  exports.prototype['returnMachineCode'] = undefined;
  /**
   * @member {Integer} returnMachineId
   */
  exports.prototype['returnMachineId'] = undefined;
  /**
   * 归还的类型，machine , repairer
   * @member {String} returnType
   */
  exports.prototype['returnType'] = undefined;
  /**
   * @member {Integer} sourceAgentId
   */
  exports.prototype['sourceAgentId'] = undefined;
  /**
   * @member {String} sourceAgentName
   */
  exports.prototype['sourceAgentName'] = undefined;
  /**
   * 金箍棒编号
   * @member {String} umbrellaCode
   */
  exports.prototype['umbrellaCode'] = undefined;



  return exports;
}));


