/**
 * 彩虹共享雨金箍棒api
 * Android、iOS操作类
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.APIAgentManageHomeBO = factory(root.Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The APIAgentManageHomeBO model module.
   * @module model/APIAgentManageHomeBO
   * @version 1.0
   */

  /**
   * Constructs a new <code>APIAgentManageHomeBO</code>.
   * @alias module:model/APIAgentManageHomeBO
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>APIAgentManageHomeBO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APIAgentManageHomeBO} obj Optional instance to populate.
   * @return {module:model/APIAgentManageHomeBO} The populated <code>APIAgentManageHomeBO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('customerServicePhone')) {
        obj['customerServicePhone'] = ApiClient.convertToType(data['customerServicePhone'], 'String');
      }
      if (data.hasOwnProperty('money')) {
        obj['money'] = ApiClient.convertToType(data['money'], 'Number');
      }
      if (data.hasOwnProperty('thisMonthProfit')) {
        obj['thisMonthProfit'] = ApiClient.convertToType(data['thisMonthProfit'], 'Number');
      }
      if (data.hasOwnProperty('totalProfit')) {
        obj['totalProfit'] = ApiClient.convertToType(data['totalProfit'], 'Number');
      }
      if (data.hasOwnProperty('yesterdayProfit')) {
        obj['yesterdayProfit'] = ApiClient.convertToType(data['yesterdayProfit'], 'Number');
      }
    }
    return obj;
  }

  /**
   * 客服电话
   * @member {String} customerServicePhone
   */
  exports.prototype['customerServicePhone'] = undefined;
  /**
   * 余额
   * @member {Number} money
   */
  exports.prototype['money'] = undefined;
  /**
   * 当月收益
   * @member {Number} thisMonthProfit
   */
  exports.prototype['thisMonthProfit'] = undefined;
  /**
   * 总收益
   * @member {Number} totalProfit
   */
  exports.prototype['totalProfit'] = undefined;
  /**
   * 昨日收益
   * @member {Number} yesterdayProfit
   */
  exports.prototype['yesterdayProfit'] = undefined;



  return exports;
}));


