/**
 * 彩虹共享雨金箍棒api
 * Android、iOS操作类
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApiPointBO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ApiPointBO'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.ApiActivityLogBO = factory(root.Api.ApiClient, root.Api.ApiPointBO);
  }
}(this, function(ApiClient, ApiPointBO) {
  'use strict';




  /**
   * The ApiActivityLogBO model module.
   * @module model/ApiActivityLogBO
   * @version 1.0
   */

  /**
   * Constructs a new <code>ApiActivityLogBO</code>.
   * @alias module:model/ApiActivityLogBO
   * @class
   */
  var exports = function() {
    var _this = this;














  };

  /**
   * Constructs a <code>ApiActivityLogBO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApiActivityLogBO} obj Optional instance to populate.
   * @return {module:model/ApiActivityLogBO} The populated <code>ApiActivityLogBO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('beginDate')) {
        obj['beginDate'] = ApiClient.convertToType(data['beginDate'], 'Date');
      }
      if (data.hasOwnProperty('calorie')) {
        obj['calorie'] = ApiClient.convertToType(data['calorie'], 'Number');
      }
      if (data.hasOwnProperty('cyclingPoints')) {
        obj['cyclingPoints'] = ApiClient.convertToType(data['cyclingPoints'], [ApiPointBO]);
      }
      if (data.hasOwnProperty('distance')) {
        obj['distance'] = ApiClient.convertToType(data['distance'], 'Number');
      }
      if (data.hasOwnProperty('endDate')) {
        obj['endDate'] = ApiClient.convertToType(data['endDate'], 'Date');
      }
      if (data.hasOwnProperty('headImgPath')) {
        obj['headImgPath'] = ApiClient.convertToType(data['headImgPath'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Integer');
      }
      if (data.hasOwnProperty('nickname')) {
        obj['nickname'] = ApiClient.convertToType(data['nickname'], 'String');
      }
      if (data.hasOwnProperty('ranking')) {
        obj['ranking'] = ApiClient.convertToType(data['ranking'], 'Integer');
      }
      if (data.hasOwnProperty('speed')) {
        obj['speed'] = ApiClient.convertToType(data['speed'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'Integer');
      }
      if (data.hasOwnProperty('useTime')) {
        obj['useTime'] = ApiClient.convertToType(data['useTime'], 'Integer');
      }
      if (data.hasOwnProperty('useTimeMapping')) {
        obj['useTimeMapping'] = ApiClient.convertToType(data['useTimeMapping'], 'String');
      }
    }
    return obj;
  }

  /**
   * 开始时间
   * @member {Date} beginDate
   */
  exports.prototype['beginDate'] = undefined;
  /**
   * 卡路里
   * @member {Number} calorie
   */
  exports.prototype['calorie'] = undefined;
  /**
   * 活动的轨迹点集合
   * @member {Array.<module:model/ApiPointBO>} cyclingPoints
   */
  exports.prototype['cyclingPoints'] = undefined;
  /**
   * 公里数
   * @member {Number} distance
   */
  exports.prototype['distance'] = undefined;
  /**
   * 结束时间
   * @member {Date} endDate
   */
  exports.prototype['endDate'] = undefined;
  /**
   * 用户头像
   * @member {String} headImgPath
   */
  exports.prototype['headImgPath'] = undefined;
  /**
   * 记录id
   * @member {Integer} id
   */
  exports.prototype['id'] = undefined;
  /**
   * 用户昵称
   * @member {String} nickname
   */
  exports.prototype['nickname'] = undefined;
  /**
   * 用户排名
   * @member {Integer} ranking
   */
  exports.prototype['ranking'] = undefined;
  /**
   * 配速
   * @member {String} speed
   */
  exports.prototype['speed'] = undefined;
  /**
   * 用户参加活动状态  10 失败，20,活动进行中，30 已成功  
   * @member {Integer} status
   */
  exports.prototype['status'] = undefined;
  /**
   * 用时
   * @member {Integer} useTime
   */
  exports.prototype['useTime'] = undefined;
  /**
   * 用时时长映射 用于客户端展示
   * @member {String} useTimeMapping
   */
  exports.prototype['useTimeMapping'] = undefined;



  return exports;
}));


