/**
 * 彩虹共享雨金箍棒api
 * Android、iOS操作类
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.APIFeedbackBO = factory(root.Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The APIFeedbackBO model module.
   * @module model/APIFeedbackBO
   * @version 1.0
   */

  /**
   * Constructs a new <code>APIFeedbackBO</code>.
   * @alias module:model/APIFeedbackBO
   * @class
   */
  var exports = function() {
    var _this = this;














  };

  /**
   * Constructs a <code>APIFeedbackBO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APIFeedbackBO} obj Optional instance to populate.
   * @return {module:model/APIFeedbackBO} The populated <code>APIFeedbackBO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('dealType')) {
        obj['dealType'] = ApiClient.convertToType(data['dealType'], 'String');
      }
      if (data.hasOwnProperty('feedDesc')) {
        obj['feedDesc'] = ApiClient.convertToType(data['feedDesc'], 'String');
      }
      if (data.hasOwnProperty('feedType')) {
        obj['feedType'] = ApiClient.convertToType(data['feedType'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Integer');
      }
      if (data.hasOwnProperty('imgUrl1')) {
        obj['imgUrl1'] = ApiClient.convertToType(data['imgUrl1'], 'String');
      }
      if (data.hasOwnProperty('imgUrl2')) {
        obj['imgUrl2'] = ApiClient.convertToType(data['imgUrl2'], 'String');
      }
      if (data.hasOwnProperty('imgUrl3')) {
        obj['imgUrl3'] = ApiClient.convertToType(data['imgUrl3'], 'String');
      }
      if (data.hasOwnProperty('imgUrl4')) {
        obj['imgUrl4'] = ApiClient.convertToType(data['imgUrl4'], 'String');
      }
      if (data.hasOwnProperty('machineCode')) {
        obj['machineCode'] = ApiClient.convertToType(data['machineCode'], 'String');
      }
      if (data.hasOwnProperty('orderCode')) {
        obj['orderCode'] = ApiClient.convertToType(data['orderCode'], 'String');
      }
      if (data.hasOwnProperty('remark')) {
        obj['remark'] = ApiClient.convertToType(data['remark'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'Integer');
      }
      if (data.hasOwnProperty('typeId')) {
        obj['typeId'] = ApiClient.convertToType(data['typeId'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * @member {String} dealType
   */
  exports.prototype['dealType'] = undefined;
  /**
   * 问题表述
   * @member {String} feedDesc
   */
  exports.prototype['feedDesc'] = undefined;
  /**
   * 类型 1：首页，2：行程中，3：已完成
   * @member {String} feedType
   */
  exports.prototype['feedType'] = undefined;
  /**
   * @member {Integer} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} imgUrl1
   */
  exports.prototype['imgUrl1'] = undefined;
  /**
   * @member {String} imgUrl2
   */
  exports.prototype['imgUrl2'] = undefined;
  /**
   * @member {String} imgUrl3
   */
  exports.prototype['imgUrl3'] = undefined;
  /**
   * @member {String} imgUrl4
   */
  exports.prototype['imgUrl4'] = undefined;
  /**
   * 棒机编号
   * @member {String} machineCode
   */
  exports.prototype['machineCode'] = undefined;
  /**
   * @member {String} orderCode
   */
  exports.prototype['orderCode'] = undefined;
  /**
   * @member {String} remark
   */
  exports.prototype['remark'] = undefined;
  /**
   *  0:已处理，1：未处理，2：无需处理 
   * @member {Integer} status
   */
  exports.prototype['status'] = undefined;
  /**
   * 问题类型id
   * @member {Integer} typeId
   */
  exports.prototype['typeId'] = undefined;



  return exports;
}));


