/**
 * 彩虹共享雨金箍棒api
 * Android、iOS操作类
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.APIOrderUmbrellaBuyBO = factory(root.Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The APIOrderUmbrellaBuyBO model module.
   * @module model/APIOrderUmbrellaBuyBO
   * @version 1.0
   */

  /**
   * Constructs a new <code>APIOrderUmbrellaBuyBO</code>.
   * @alias module:model/APIOrderUmbrellaBuyBO
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>APIOrderUmbrellaBuyBO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APIOrderUmbrellaBuyBO} obj Optional instance to populate.
   * @return {module:model/APIOrderUmbrellaBuyBO} The populated <code>APIOrderUmbrellaBuyBO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('buyOrderDesc')) {
        obj['buyOrderDesc'] = ApiClient.convertToType(data['buyOrderDesc'], 'String');
      }
      if (data.hasOwnProperty('orderCode')) {
        obj['orderCode'] = ApiClient.convertToType(data['orderCode'], 'String');
      }
      if (data.hasOwnProperty('orderId')) {
        obj['orderId'] = ApiClient.convertToType(data['orderId'], 'Integer');
      }
      if (data.hasOwnProperty('payAmout')) {
        obj['payAmout'] = ApiClient.convertToType(data['payAmout'], 'Number');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'Integer');
      }
      if (data.hasOwnProperty('umbrellaCode')) {
        obj['umbrellaCode'] = ApiClient.convertToType(data['umbrellaCode'], 'String');
      }
      if (data.hasOwnProperty('umbrellaId')) {
        obj['umbrellaId'] = ApiClient.convertToType(data['umbrellaId'], 'Integer');
      }
      if (data.hasOwnProperty('umbrellaPrice')) {
        obj['umbrellaPrice'] = ApiClient.convertToType(data['umbrellaPrice'], 'Number');
      }
    }
    return obj;
  }

  /**
   * 目前订单描述
   * @member {String} buyOrderDesc
   */
  exports.prototype['buyOrderDesc'] = undefined;
  /**
   * 订单编号
   * @member {String} orderCode
   */
  exports.prototype['orderCode'] = undefined;
  /**
   * @member {Integer} orderId
   */
  exports.prototype['orderId'] = undefined;
  /**
   * @member {Number} payAmout
   */
  exports.prototype['payAmout'] = undefined;
  /**
   * 1 待购买，2 已成功
   * @member {Integer} status
   */
  exports.prototype['status'] = undefined;
  /**
   * 金箍棒编号 
   * @member {String} umbrellaCode
   */
  exports.prototype['umbrellaCode'] = undefined;
  /**
   * @member {Integer} umbrellaId
   */
  exports.prototype['umbrellaId'] = undefined;
  /**
   * 雨金箍棒价格
   * @member {Number} umbrellaPrice
   */
  exports.prototype['umbrellaPrice'] = undefined;



  return exports;
}));


