/**
 * 彩虹共享雨金箍棒api
 * Android、iOS操作类
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.ApiPointBO = factory(root.Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ApiPointBO model module.
   * @module model/ApiPointBO
   * @version 1.0
   */

  /**
   * Constructs a new <code>ApiPointBO</code>.
   * @alias module:model/ApiPointBO
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ApiPointBO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApiPointBO} obj Optional instance to populate.
   * @return {module:model/ApiPointBO} The populated <code>ApiPointBO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('pointLat')) {
        obj['pointLat'] = ApiClient.convertToType(data['pointLat'], 'Number');
      }
      if (data.hasOwnProperty('pointLon')) {
        obj['pointLon'] = ApiClient.convertToType(data['pointLon'], 'Number');
      }
    }
    return obj;
  }

  /**
   * 纬度 
   * @member {Number} pointLat
   */
  exports.prototype['pointLat'] = undefined;
  /**
   * 经度 
   * @member {Number} pointLon
   */
  exports.prototype['pointLon'] = undefined;



  return exports;
}));


