/**
 * 彩虹共享雨金箍棒api
 * Android、iOS操作类
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/APIUserMoneyCashBO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./APIUserMoneyCashBO'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.APIUserMoneyCashGroupBO = factory(root.Api.ApiClient, root.Api.APIUserMoneyCashBO);
  }
}(this, function(ApiClient, APIUserMoneyCashBO) {
  'use strict';




  /**
   * The APIUserMoneyCashGroupBO model module.
   * @module model/APIUserMoneyCashGroupBO
   * @version 1.0
   */

  /**
   * Constructs a new <code>APIUserMoneyCashGroupBO</code>.
   * @alias module:model/APIUserMoneyCashGroupBO
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>APIUserMoneyCashGroupBO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APIUserMoneyCashGroupBO} obj Optional instance to populate.
   * @return {module:model/APIUserMoneyCashGroupBO} The populated <code>APIUserMoneyCashGroupBO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('date')) {
        obj['date'] = ApiClient.convertToType(data['date'], 'Date');
      }
      if (data.hasOwnProperty('list')) {
        obj['list'] = ApiClient.convertToType(data['list'], [APIUserMoneyCashBO]);
      }
    }
    return obj;
  }

  /**
   * @member {Date} date
   */
  exports.prototype['date'] = undefined;
  /**
   * @member {Array.<module:model/APIUserMoneyCashBO>} list
   */
  exports.prototype['list'] = undefined;



  return exports;
}));


