/**
 * 彩虹共享雨金箍棒api
 * Android、iOS操作类
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.APIUmbrellaDistributeBO = factory(root.Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The APIUmbrellaDistributeBO model module.
   * @module model/APIUmbrellaDistributeBO
   * @version 1.0
   */

  /**
   * Constructs a new <code>APIUmbrellaDistributeBO</code>.
   * @alias module:model/APIUmbrellaDistributeBO
   * @class
   */
  var exports = function() {
    var _this = this;





















  };

  /**
   * Constructs a <code>APIUmbrellaDistributeBO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APIUmbrellaDistributeBO} obj Optional instance to populate.
   * @return {module:model/APIUmbrellaDistributeBO} The populated <code>APIUmbrellaDistributeBO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('agentId')) {
        obj['agentId'] = ApiClient.convertToType(data['agentId'], 'Integer');
      }
      if (data.hasOwnProperty('agentLocationAddress')) {
        obj['agentLocationAddress'] = ApiClient.convertToType(data['agentLocationAddress'], 'String');
      }
      if (data.hasOwnProperty('agentLocationDesc')) {
        obj['agentLocationDesc'] = ApiClient.convertToType(data['agentLocationDesc'], 'String');
      }
      if (data.hasOwnProperty('agentLocationLat')) {
        obj['agentLocationLat'] = ApiClient.convertToType(data['agentLocationLat'], 'Number');
      }
      if (data.hasOwnProperty('agentLocationLon')) {
        obj['agentLocationLon'] = ApiClient.convertToType(data['agentLocationLon'], 'Number');
      }
      if (data.hasOwnProperty('agentName')) {
        obj['agentName'] = ApiClient.convertToType(data['agentName'], 'String');
      }
      if (data.hasOwnProperty('contactMobile')) {
        obj['contactMobile'] = ApiClient.convertToType(data['contactMobile'], 'String');
      }
      if (data.hasOwnProperty('contactName')) {
        obj['contactName'] = ApiClient.convertToType(data['contactName'], 'String');
      }
      if (data.hasOwnProperty('createTime')) {
        obj['createTime'] = ApiClient.convertToType(data['createTime'], 'Date');
      }
      if (data.hasOwnProperty('distributeMachineCode')) {
        obj['distributeMachineCode'] = ApiClient.convertToType(data['distributeMachineCode'], 'String');
      }
      if (data.hasOwnProperty('distributeMachineId')) {
        obj['distributeMachineId'] = ApiClient.convertToType(data['distributeMachineId'], 'Integer');
      }
      if (data.hasOwnProperty('distributeType')) {
        obj['distributeType'] = ApiClient.convertToType(data['distributeType'], 'String');
      }
      if (data.hasOwnProperty('machineLocationAddress')) {
        obj['machineLocationAddress'] = ApiClient.convertToType(data['machineLocationAddress'], 'String');
      }
      if (data.hasOwnProperty('machineLocationDesc')) {
        obj['machineLocationDesc'] = ApiClient.convertToType(data['machineLocationDesc'], 'String');
      }
      if (data.hasOwnProperty('machineLocationLat')) {
        obj['machineLocationLat'] = ApiClient.convertToType(data['machineLocationLat'], 'Number');
      }
      if (data.hasOwnProperty('machineLocationLon')) {
        obj['machineLocationLon'] = ApiClient.convertToType(data['machineLocationLon'], 'Number');
      }
      if (data.hasOwnProperty('receiveTime')) {
        obj['receiveTime'] = ApiClient.convertToType(data['receiveTime'], 'Date');
      }
      if (data.hasOwnProperty('repairerName')) {
        obj['repairerName'] = ApiClient.convertToType(data['repairerName'], 'String');
      }
      if (data.hasOwnProperty('umbrellaCode')) {
        obj['umbrellaCode'] = ApiClient.convertToType(data['umbrellaCode'], 'String');
      }
      if (data.hasOwnProperty('umbrellaId')) {
        obj['umbrellaId'] = ApiClient.convertToType(data['umbrellaId'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * @member {Integer} agentId
   */
  exports.prototype['agentId'] = undefined;
  /**
   * @member {String} agentLocationAddress
   */
  exports.prototype['agentLocationAddress'] = undefined;
  /**
   * @member {String} agentLocationDesc
   */
  exports.prototype['agentLocationDesc'] = undefined;
  /**
   * @member {Number} agentLocationLat
   */
  exports.prototype['agentLocationLat'] = undefined;
  /**
   * @member {Number} agentLocationLon
   */
  exports.prototype['agentLocationLon'] = undefined;
  /**
   * @member {String} agentName
   */
  exports.prototype['agentName'] = undefined;
  /**
   * @member {String} contactMobile
   */
  exports.prototype['contactMobile'] = undefined;
  /**
   * @member {String} contactName
   */
  exports.prototype['contactName'] = undefined;
  /**
   * @member {Date} createTime
   */
  exports.prototype['createTime'] = undefined;
  /**
   * @member {String} distributeMachineCode
   */
  exports.prototype['distributeMachineCode'] = undefined;
  /**
   * @member {Integer} distributeMachineId
   */
  exports.prototype['distributeMachineId'] = undefined;
  /**
   * @member {String} distributeType
   */
  exports.prototype['distributeType'] = undefined;
  /**
   * @member {String} machineLocationAddress
   */
  exports.prototype['machineLocationAddress'] = undefined;
  /**
   * @member {String} machineLocationDesc
   */
  exports.prototype['machineLocationDesc'] = undefined;
  /**
   * @member {Number} machineLocationLat
   */
  exports.prototype['machineLocationLat'] = undefined;
  /**
   * @member {Number} machineLocationLon
   */
  exports.prototype['machineLocationLon'] = undefined;
  /**
   * 接收时间
   * @member {Date} receiveTime
   */
  exports.prototype['receiveTime'] = undefined;
  /**
   * @member {String} repairerName
   */
  exports.prototype['repairerName'] = undefined;
  /**
   * @member {String} umbrellaCode
   */
  exports.prototype['umbrellaCode'] = undefined;
  /**
   * @member {Integer} umbrellaId
   */
  exports.prototype['umbrellaId'] = undefined;



  return exports;
}));


