/**
 * 彩虹共享雨金箍棒api
 * Android、iOS操作类
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.APIUserMoneyCashBO = factory(root.Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The APIUserMoneyCashBO model module.
   * @module model/APIUserMoneyCashBO
   * @version 1.0
   */

  /**
   * Constructs a new <code>APIUserMoneyCashBO</code>.
   * @alias module:model/APIUserMoneyCashBO
   * @class
   */
  var exports = function() {
    var _this = this;

















  };

  /**
   * Constructs a <code>APIUserMoneyCashBO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APIUserMoneyCashBO} obj Optional instance to populate.
   * @return {module:model/APIUserMoneyCashBO} The populated <code>APIUserMoneyCashBO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('balance')) {
        obj['balance'] = ApiClient.convertToType(data['balance'], 'Number');
      }
      if (data.hasOwnProperty('cashAccount')) {
        obj['cashAccount'] = ApiClient.convertToType(data['cashAccount'], 'String');
      }
      if (data.hasOwnProperty('cashAdminId')) {
        obj['cashAdminId'] = ApiClient.convertToType(data['cashAdminId'], 'Integer');
      }
      if (data.hasOwnProperty('cashAdminInfo')) {
        obj['cashAdminInfo'] = ApiClient.convertToType(data['cashAdminInfo'], 'String');
      }
      if (data.hasOwnProperty('cashAmount')) {
        obj['cashAmount'] = ApiClient.convertToType(data['cashAmount'], 'Number');
      }
      if (data.hasOwnProperty('cashBank')) {
        obj['cashBank'] = ApiClient.convertToType(data['cashBank'], 'String');
      }
      if (data.hasOwnProperty('cashInfo')) {
        obj['cashInfo'] = ApiClient.convertToType(data['cashInfo'], 'String');
      }
      if (data.hasOwnProperty('cashPaymentType')) {
        obj['cashPaymentType'] = ApiClient.convertToType(data['cashPaymentType'], 'String');
      }
      if (data.hasOwnProperty('cashSn')) {
        obj['cashSn'] = ApiClient.convertToType(data['cashSn'], 'String');
      }
      if (data.hasOwnProperty('cashStatus')) {
        obj['cashStatus'] = ApiClient.convertToType(data['cashStatus'], 'String');
      }
      if (data.hasOwnProperty('cashUserId')) {
        obj['cashUserId'] = ApiClient.convertToType(data['cashUserId'], 'Integer');
      }
      if (data.hasOwnProperty('cashUserName')) {
        obj['cashUserName'] = ApiClient.convertToType(data['cashUserName'], 'String');
      }
      if (data.hasOwnProperty('checkTime')) {
        obj['checkTime'] = ApiClient.convertToType(data['checkTime'], 'Date');
      }
      if (data.hasOwnProperty('createTime')) {
        obj['createTime'] = ApiClient.convertToType(data['createTime'], 'Date');
      }
      if (data.hasOwnProperty('loginName')) {
        obj['loginName'] = ApiClient.convertToType(data['loginName'], 'String');
      }
      if (data.hasOwnProperty('transTime')) {
        obj['transTime'] = ApiClient.convertToType(data['transTime'], 'Date');
      }
    }
    return obj;
  }

  /**
   * 余额
   * @member {Number} balance
   */
  exports.prototype['balance'] = undefined;
  /**
   * 收款账号
   * @member {String} cashAccount
   */
  exports.prototype['cashAccount'] = undefined;
  /**
   * @member {Integer} cashAdminId
   */
  exports.prototype['cashAdminId'] = undefined;
  /**
   * 请求处理备注
   * @member {String} cashAdminInfo
   */
  exports.prototype['cashAdminInfo'] = undefined;
  /**
   * 提现金额
   * @member {Number} cashAmount
   */
  exports.prototype['cashAmount'] = undefined;
  /**
   * 收款银行
   * @member {String} cashBank
   */
  exports.prototype['cashBank'] = undefined;
  /**
   * 提现备注
   * @member {String} cashInfo
   */
  exports.prototype['cashInfo'] = undefined;
  /**
   * @member {String} cashPaymentType
   */
  exports.prototype['cashPaymentType'] = undefined;
  /**
   * 提现编号
   * @member {String} cashSn
   */
  exports.prototype['cashSn'] = undefined;
  /**
   * 收款支付状态，1为未审核，2为等待支付，3为支付完成，4为审核失败
   * @member {String} cashStatus
   */
  exports.prototype['cashStatus'] = undefined;
  /**
   * @member {Integer} cashUserId
   */
  exports.prototype['cashUserId'] = undefined;
  /**
   * 收款人姓名
   * @member {String} cashUserName
   */
  exports.prototype['cashUserName'] = undefined;
  /**
   * @member {Date} checkTime
   */
  exports.prototype['checkTime'] = undefined;
  /**
   * @member {Date} createTime
   */
  exports.prototype['createTime'] = undefined;
  /**
   * @member {String} loginName
   */
  exports.prototype['loginName'] = undefined;
  /**
   * 转账时间
   * @member {Date} transTime
   */
  exports.prototype['transTime'] = undefined;



  return exports;
}));


