/**
 * 彩虹共享雨金箍棒api
 * Android、iOS操作类
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.CompleteOrderVO = factory(root.Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CompleteOrderVO model module.
   * @module model/CompleteOrderVO
   * @version 1.0
   */

  /**
   * Constructs a new <code>CompleteOrderVO</code>.
   * @alias module:model/CompleteOrderVO
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>CompleteOrderVO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CompleteOrderVO} obj Optional instance to populate.
   * @return {module:model/CompleteOrderVO} The populated <code>CompleteOrderVO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('completeStatus')) {
        obj['completeStatus'] = ApiClient.convertToType(data['completeStatus'], 'String');
      }
      if (data.hasOwnProperty('dealImgs')) {
        obj['dealImgs'] = ApiClient.convertToType(data['dealImgs'], ['String']);
      }
      if (data.hasOwnProperty('dealRemark')) {
        obj['dealRemark'] = ApiClient.convertToType(data['dealRemark'], 'String');
      }
      if (data.hasOwnProperty('orderCode')) {
        obj['orderCode'] = ApiClient.convertToType(data['orderCode'], 'String');
      }
      if (data.hasOwnProperty('pointType')) {
        obj['pointType'] = ApiClient.convertToType(data['pointType'], 'String');
      }
      if (data.hasOwnProperty('x')) {
        obj['x'] = ApiClient.convertToType(data['x'], 'Number');
      }
      if (data.hasOwnProperty('y')) {
        obj['y'] = ApiClient.convertToType(data['y'], 'Number');
      }
    }
    return obj;
  }

  /**
   * 1,正常完成，2 异常完成
   * @member {String} completeStatus
   */
  exports.prototype['completeStatus'] = undefined;
  /**
   * @member {Array.<String>} dealImgs
   */
  exports.prototype['dealImgs'] = undefined;
  /**
   * @member {String} dealRemark
   */
  exports.prototype['dealRemark'] = undefined;
  /**
   * @member {String} orderCode
   */
  exports.prototype['orderCode'] = undefined;
  /**
   * @member {String} pointType
   */
  exports.prototype['pointType'] = undefined;
  /**
   * @member {Number} x
   */
  exports.prototype['x'] = undefined;
  /**
   * @member {Number} y
   */
  exports.prototype['y'] = undefined;



  return exports;
}));


