/**
 * 彩虹共享雨金箍棒api
 * Android、iOS操作类
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InitImgBO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InitImgBO'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.ImgBo = factory(root.Api.ApiClient, root.Api.InitImgBO);
  }
}(this, function(ApiClient, InitImgBO) {
  'use strict';




  /**
   * The ImgBo model module.
   * @module model/ImgBo
   * @version 1.0
   */

  /**
   * Constructs a new <code>ImgBo</code>.
   * @alias module:model/ImgBo
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>ImgBo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ImgBo} obj Optional instance to populate.
   * @return {module:model/ImgBo} The populated <code>ImgBo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('imgList')) {
        obj['imgList'] = ApiClient.convertToType(data['imgList'], [InitImgBO]);
      }
      if (data.hasOwnProperty('md5')) {
        obj['md5'] = ApiClient.convertToType(data['md5'], 'String');
      }
      if (data.hasOwnProperty('time')) {
        obj['time'] = ApiClient.convertToType(data['time'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/InitImgBO>} imgList
   */
  exports.prototype['imgList'] = undefined;
  /**
   * @member {String} md5
   */
  exports.prototype['md5'] = undefined;
  /**
   * @member {Integer} time
   */
  exports.prototype['time'] = undefined;



  return exports;
}));


