/**
 * 彩虹共享雨金箍棒api
 * Android、iOS操作类
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.MemberBO = factory(root.Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MemberBO model module.
   * @module model/MemberBO
   * @version 1.0
   */

  /**
   * Constructs a new <code>MemberBO</code>.
   * @alias module:model/MemberBO
   * @class
   */
  var exports = function() {
    var _this = this;





















  };

  /**
   * Constructs a <code>MemberBO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MemberBO} obj Optional instance to populate.
   * @return {module:model/MemberBO} The populated <code>MemberBO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('authStatus')) {
        obj['authStatus'] = ApiClient.convertToType(data['authStatus'], 'String');
      }
      if (data.hasOwnProperty('authStep')) {
        obj['authStep'] = ApiClient.convertToType(data['authStep'], 'Integer');
      }
      if (data.hasOwnProperty('birthdate')) {
        obj['birthdate'] = ApiClient.convertToType(data['birthdate'], 'Date');
      }
      if (data.hasOwnProperty('calorie')) {
        obj['calorie'] = ApiClient.convertToType(data['calorie'], 'Number');
      }
      if (data.hasOwnProperty('deposit')) {
        obj['deposit'] = ApiClient.convertToType(data['deposit'], 'Number');
      }
      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('headImgPath')) {
        obj['headImgPath'] = ApiClient.convertToType(data['headImgPath'], 'String');
      }
      if (data.hasOwnProperty('height')) {
        obj['height'] = ApiClient.convertToType(data['height'], 'Integer');
      }
      if (data.hasOwnProperty('idCard')) {
        obj['idCard'] = ApiClient.convertToType(data['idCard'], 'String');
      }
      if (data.hasOwnProperty('inviteCode')) {
        obj['inviteCode'] = ApiClient.convertToType(data['inviteCode'], 'String');
      }
      if (data.hasOwnProperty('isAuthByMayi')) {
        obj['isAuthByMayi'] = ApiClient.convertToType(data['isAuthByMayi'], 'Boolean');
      }
      if (data.hasOwnProperty('mobile')) {
        obj['mobile'] = ApiClient.convertToType(data['mobile'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('nickname')) {
        obj['nickname'] = ApiClient.convertToType(data['nickname'], 'String');
      }
      if (data.hasOwnProperty('rainfall')) {
        obj['rainfall'] = ApiClient.convertToType(data['rainfall'], 'Number');
      }
      if (data.hasOwnProperty('remark')) {
        obj['remark'] = ApiClient.convertToType(data['remark'], 'String');
      }
      if (data.hasOwnProperty('sex')) {
        obj['sex'] = ApiClient.convertToType(data['sex'], 'Integer');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('useTime')) {
        obj['useTime'] = ApiClient.convertToType(data['useTime'], 'Integer');
      }
      if (data.hasOwnProperty('weight')) {
        obj['weight'] = ApiClient.convertToType(data['weight'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * 认证状态：0未认证，1认证中，2认证成功，3认证失败
   * @member {String} authStatus
   */
  exports.prototype['authStatus'] = undefined;
  /**
   * 认证步骤：1.手机认证,2. 押金充值 3.实名认证 4.认证完成
   * @member {Integer} authStep
   */
  exports.prototype['authStep'] = undefined;
  /**
   * @member {Date} birthdate
   */
  exports.prototype['birthdate'] = undefined;
  /**
   * 消耗热量kcal 
   * @member {Number} calorie
   */
  exports.prototype['calorie'] = undefined;
  /**
   * 押金
   * @member {Number} deposit
   */
  exports.prototype['deposit'] = undefined;
  /**
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * 头像路径 
   * @member {String} headImgPath
   */
  exports.prototype['headImgPath'] = undefined;
  /**
   * @member {Integer} height
   */
  exports.prototype['height'] = undefined;
  /**
   * 身份证
   * @member {String} idCard
   */
  exports.prototype['idCard'] = undefined;
  /**
   * 邀请码
   * @member {String} inviteCode
   */
  exports.prototype['inviteCode'] = undefined;
  /**
   * 是否经过芝麻信用免押金
   * @member {Boolean} isAuthByMayi
   */
  exports.prototype['isAuthByMayi'] = undefined;
  /**
   * 手机 
   * @member {String} mobile
   */
  exports.prototype['mobile'] = undefined;
  /**
   * 姓名 
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * 昵称 
   * @member {String} nickname
   */
  exports.prototype['nickname'] = undefined;
  /**
   * 挡雨量
   * @member {Number} rainfall
   */
  exports.prototype['rainfall'] = undefined;
  /**
   * 备注
   * @member {String} remark
   */
  exports.prototype['remark'] = undefined;
  /**
   * 性别 1，男 2，女
   * @member {Integer} sex
   */
  exports.prototype['sex'] = undefined;
  /**
   * 状态 1:正常 2：未激活,3禁用
   * @member {String} status
   */
  exports.prototype['status'] = undefined;
  /**
   * 使用时间/分钟
   * @member {Integer} useTime
   */
  exports.prototype['useTime'] = undefined;
  /**
   * @member {Integer} weight
   */
  exports.prototype['weight'] = undefined;



  return exports;
}));


