/**
 * 彩虹共享雨金箍棒api
 * Android、iOS操作类
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/View'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./View'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.ModelAndView = factory(root.Api.ApiClient, root.Api.View);
  }
}(this, function(ApiClient, View) {
  'use strict';




  /**
   * The ModelAndView model module.
   * @module model/ModelAndView
   * @version 1.0
   */

  /**
   * Constructs a new <code>ModelAndView</code>.
   * @alias module:model/ModelAndView
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>ModelAndView</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelAndView} obj Optional instance to populate.
   * @return {module:model/ModelAndView} The populated <code>ModelAndView</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('empty')) {
        obj['empty'] = ApiClient.convertToType(data['empty'], 'Boolean');
      }
      if (data.hasOwnProperty('model')) {
        obj['model'] = ApiClient.convertToType(data['model'], Object);
      }
      if (data.hasOwnProperty('modelMap')) {
        obj['modelMap'] = ApiClient.convertToType(data['modelMap'], {'String': Object});
      }
      if (data.hasOwnProperty('reference')) {
        obj['reference'] = ApiClient.convertToType(data['reference'], 'Boolean');
      }
      if (data.hasOwnProperty('view')) {
        obj['view'] = View.constructFromObject(data['view']);
      }
      if (data.hasOwnProperty('viewName')) {
        obj['viewName'] = ApiClient.convertToType(data['viewName'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} empty
   */
  exports.prototype['empty'] = undefined;
  /**
   * @member {Object} model
   */
  exports.prototype['model'] = undefined;
  /**
   * @member {Object.<String, Object>} modelMap
   */
  exports.prototype['modelMap'] = undefined;
  /**
   * @member {Boolean} reference
   */
  exports.prototype['reference'] = undefined;
  /**
   * @member {module:model/View} view
   */
  exports.prototype['view'] = undefined;
  /**
   * @member {String} viewName
   */
  exports.prototype['viewName'] = undefined;



  return exports;
}));


