/**
 * 彩虹共享雨金箍棒api
 * Android、iOS操作类
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/WeiXinPaymetBO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./WeiXinPaymetBO'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.PayDetailsBO = factory(root.Api.ApiClient, root.Api.WeiXinPaymetBO);
  }
}(this, function(ApiClient, WeiXinPaymetBO) {
  'use strict';




  /**
   * The PayDetailsBO model module.
   * @module model/PayDetailsBO
   * @version 1.0
   */

  /**
   * Constructs a new <code>PayDetailsBO</code>.
   * @alias module:model/PayDetailsBO
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>PayDetailsBO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PayDetailsBO} obj Optional instance to populate.
   * @return {module:model/PayDetailsBO} The populated <code>PayDetailsBO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('alipaPpaySignature')) {
        obj['alipaPpaySignature'] = ApiClient.convertToType(data['alipaPpaySignature'], 'String');
      }
      if (data.hasOwnProperty('weiXinPaymet')) {
        obj['weiXinPaymet'] = WeiXinPaymetBO.constructFromObject(data['weiXinPaymet']);
      }
    }
    return obj;
  }

  /**
   * @member {String} alipaPpaySignature
   */
  exports.prototype['alipaPpaySignature'] = undefined;
  /**
   * @member {module:model/WeiXinPaymetBO} weiXinPaymet
   */
  exports.prototype['weiXinPaymet'] = undefined;



  return exports;
}));


