/**
 * 彩虹共享雨金箍棒api
 * Android、iOS操作类
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.ShareSetBO = factory(root.Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ShareSetBO model module.
   * @module model/ShareSetBO
   * @version 1.0
   */

  /**
   * Constructs a new <code>ShareSetBO</code>.
   * @alias module:model/ShareSetBO
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>ShareSetBO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ShareSetBO} obj Optional instance to populate.
   * @return {module:model/ShareSetBO} The populated <code>ShareSetBO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('inviteContent')) {
        obj['inviteContent'] = ApiClient.convertToType(data['inviteContent'], 'String');
      }
      if (data.hasOwnProperty('inviteTitle')) {
        obj['inviteTitle'] = ApiClient.convertToType(data['inviteTitle'], 'String');
      }
      if (data.hasOwnProperty('inviteWay')) {
        obj['inviteWay'] = ApiClient.convertToType(data['inviteWay'], 'String');
      }
      if (data.hasOwnProperty('scenicShareContent')) {
        obj['scenicShareContent'] = ApiClient.convertToType(data['scenicShareContent'], 'String');
      }
      if (data.hasOwnProperty('scenicShareTitle')) {
        obj['scenicShareTitle'] = ApiClient.convertToType(data['scenicShareTitle'], 'String');
      }
      if (data.hasOwnProperty('scenicShareWay')) {
        obj['scenicShareWay'] = ApiClient.convertToType(data['scenicShareWay'], 'String');
      }
      if (data.hasOwnProperty('shareContent')) {
        obj['shareContent'] = ApiClient.convertToType(data['shareContent'], 'String');
      }
      if (data.hasOwnProperty('shareTitle')) {
        obj['shareTitle'] = ApiClient.convertToType(data['shareTitle'], 'String');
      }
      if (data.hasOwnProperty('shareWay')) {
        obj['shareWay'] = ApiClient.convertToType(data['shareWay'], 'String');
      }
      if (data.hasOwnProperty('weatherShareContent')) {
        obj['weatherShareContent'] = ApiClient.convertToType(data['weatherShareContent'], 'String');
      }
      if (data.hasOwnProperty('weatherShareTitle')) {
        obj['weatherShareTitle'] = ApiClient.convertToType(data['weatherShareTitle'], 'String');
      }
      if (data.hasOwnProperty('weatherShareWay')) {
        obj['weatherShareWay'] = ApiClient.convertToType(data['weatherShareWay'], 'String');
      }
    }
    return obj;
  }

  /**
   * 邀请好友内容 
   * @member {String} inviteContent
   */
  exports.prototype['inviteContent'] = undefined;
  /**
   * 邀请好友标题 
   * @member {String} inviteTitle
   */
  exports.prototype['inviteTitle'] = undefined;
  /**
   * 邀请好友途径 1，微信，2朋友圈，3QQ,4QQ空间
   * @member {String} inviteWay
   */
  exports.prototype['inviteWay'] = undefined;
  /**
   * 景区消息内容
   * @member {String} scenicShareContent
   */
  exports.prototype['scenicShareContent'] = undefined;
  /**
   * 景区消息标题
   * @member {String} scenicShareTitle
   */
  exports.prototype['scenicShareTitle'] = undefined;
  /**
   * 景区消息途径
   * @member {String} scenicShareWay
   */
  exports.prototype['scenicShareWay'] = undefined;
  /**
   * 行程分享内容
   * @member {String} shareContent
   */
  exports.prototype['shareContent'] = undefined;
  /**
   * 行程分享标题 
   * @member {String} shareTitle
   */
  exports.prototype['shareTitle'] = undefined;
  /**
   * 行程分享途径 1，微信，2朋友圈，3QQ,4QQ空间 
   * @member {String} shareWay
   */
  exports.prototype['shareWay'] = undefined;
  /**
   * 天气分享内容 
   * @member {String} weatherShareContent
   */
  exports.prototype['weatherShareContent'] = undefined;
  /**
   * 天气分享标题 
   * @member {String} weatherShareTitle
   */
  exports.prototype['weatherShareTitle'] = undefined;
  /**
   * 天气分享途径 1，微信，2朋友圈，3QQ,4QQ空间
   * @member {String} weatherShareWay
   */
  exports.prototype['weatherShareWay'] = undefined;



  return exports;
}));


