/**
 * 彩虹共享雨金箍棒api
 * Android、iOS操作类
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.SysSettingBO = factory(root.Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SysSettingBO model module.
   * @module model/SysSettingBO
   * @version 1.0
   */

  /**
   * Constructs a new <code>SysSettingBO</code>.
   * @alias module:model/SysSettingBO
   * @class
   */
  var exports = function() {
    var _this = this;

















  };

  /**
   * Constructs a <code>SysSettingBO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SysSettingBO} obj Optional instance to populate.
   * @return {module:model/SysSettingBO} The populated <code>SysSettingBO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('androidDownloadUrl')) {
        obj['androidDownloadUrl'] = ApiClient.convertToType(data['androidDownloadUrl'], 'String');
      }
      if (data.hasOwnProperty('appDownloadUrl')) {
        obj['appDownloadUrl'] = ApiClient.convertToType(data['appDownloadUrl'], 'String');
      }
      if (data.hasOwnProperty('appName')) {
        obj['appName'] = ApiClient.convertToType(data['appName'], 'String');
      }
      if (data.hasOwnProperty('communicationIp')) {
        obj['communicationIp'] = ApiClient.convertToType(data['communicationIp'], 'String');
      }
      if (data.hasOwnProperty('communicationPort')) {
        obj['communicationPort'] = ApiClient.convertToType(data['communicationPort'], 'Integer');
      }
      if (data.hasOwnProperty('contactMobile')) {
        obj['contactMobile'] = ApiClient.convertToType(data['contactMobile'], 'String');
      }
      if (data.hasOwnProperty('corporateName')) {
        obj['corporateName'] = ApiClient.convertToType(data['corporateName'], 'String');
      }
      if (data.hasOwnProperty('defaultLanguage')) {
        obj['defaultLanguage'] = ApiClient.convertToType(data['defaultLanguage'], 'String');
      }
      if (data.hasOwnProperty('iosDownloadUrl')) {
        obj['iosDownloadUrl'] = ApiClient.convertToType(data['iosDownloadUrl'], 'String');
      }
      if (data.hasOwnProperty('isAllosShareImagetext')) {
        obj['isAllosShareImagetext'] = ApiClient.convertToType(data['isAllosShareImagetext'], 'Boolean');
      }
      if (data.hasOwnProperty('logoImg')) {
        obj['logoImg'] = ApiClient.convertToType(data['logoImg'], 'String');
      }
      if (data.hasOwnProperty('marketingModel')) {
        obj['marketingModel'] = ApiClient.convertToType(data['marketingModel'], 'Integer');
      }
      if (data.hasOwnProperty('payWay')) {
        obj['payWay'] = ApiClient.convertToType(data['payWay'], 'String');
      }
      if (data.hasOwnProperty('reserveNum')) {
        obj['reserveNum'] = ApiClient.convertToType(data['reserveNum'], 'Integer');
      }
      if (data.hasOwnProperty('reserveTime')) {
        obj['reserveTime'] = ApiClient.convertToType(data['reserveTime'], 'Integer');
      }
      if (data.hasOwnProperty('umbrellaBuyNotice')) {
        obj['umbrellaBuyNotice'] = ApiClient.convertToType(data['umbrellaBuyNotice'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} androidDownloadUrl
   */
  exports.prototype['androidDownloadUrl'] = undefined;
  /**
   * @member {String} appDownloadUrl
   */
  exports.prototype['appDownloadUrl'] = undefined;
  /**
   * 应用名称
   * @member {String} appName
   */
  exports.prototype['appName'] = undefined;
  /**
   * 通讯 ip
   * @member {String} communicationIp
   */
  exports.prototype['communicationIp'] = undefined;
  /**
   * 通讯端口
   * @member {Integer} communicationPort
   */
  exports.prototype['communicationPort'] = undefined;
  /**
   * 联系电话
   * @member {String} contactMobile
   */
  exports.prototype['contactMobile'] = undefined;
  /**
   * 公司名称
   * @member {String} corporateName
   */
  exports.prototype['corporateName'] = undefined;
  /**
   * 1 简体中文 ，2 英语 
   * @member {String} defaultLanguage
   */
  exports.prototype['defaultLanguage'] = undefined;
  /**
   * @member {String} iosDownloadUrl
   */
  exports.prototype['iosDownloadUrl'] = undefined;
  /**
   * 是否允许分享图文
   * @member {Boolean} isAllosShareImagetext
   */
  exports.prototype['isAllosShareImagetext'] = undefined;
  /**
   * logo 地址
   * @member {String} logoImg
   */
  exports.prototype['logoImg'] = undefined;
  /**
   * 1：金箍棒机，2：网点，3：棒机和驿站
   * @member {Integer} marketingModel
   */
  exports.prototype['marketingModel'] = undefined;
  /**
   * 1 微信 ，2 支付宝  ， 1,2 微信和支付宝 
   * @member {String} payWay
   */
  exports.prototype['payWay'] = undefined;
  /**
   * 一天预约次数限制
   * @member {Integer} reserveNum
   */
  exports.prototype['reserveNum'] = undefined;
  /**
   * 预约时间/单位分钟
   * @member {Integer} reserveTime
   */
  exports.prototype['reserveTime'] = undefined;
  /**
   * 雨金箍棒购买须知
   * @member {String} umbrellaBuyNotice
   */
  exports.prototype['umbrellaBuyNotice'] = undefined;



  return exports;
}));


